services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4523
      - DB_PATH=/data/erp.sqlite
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4523/api
    ports:
      - "4523:4523"
    volumes:
      - ./data:/data
    restart: unless-stopped
