services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8001
      - CORS_ORIGIN=http://frontend:4522,http://localhost:4522
      - DB_PATH=/app/data/erp.sqlite
      - NODE_ENV=production
    ports:
      - "8001:8001"
    volumes:
      - ./backend/data:/app/data
    networks:
      - erp-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - NODE_ENV=production
      - PORT=4522
    ports:
      - "4522:4522"
    depends_on:
      - backend
    networks:
      - erp-network
    restart: unless-stopped

networks:
  erp-network:
    driver: bridge
