services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3145
      - DB_PATH=/data/erp.sqlite
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3145/api
    ports:
      - "3145:3145"
    volumes:
      - ./data:/data
    restart: unless-stopped
